[app]
title = My Kivy App
package.name = mykivyapp
package.domain = org.abdullah
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
source.exclude_dirs = tests, test, bin, venv, .buildozer
version = 0.1
requirements = python3,kivy,numpy,sympy,pillow,requests
orientation = portrait
osx.kivy_version = 2.1.0
fullscreen = 1
android.permissions = INTERNET
android.archs = arm64-v8a, armeabi-v7a
android.allow_backup = True
android.api = 34
android.minapi = 21
android.ndk = 25c
android.private_storage = True
android.logcat_filters = *:S python:D
android.logcat_pid = False
android.copy_libs = 1
